language: swift
osx_image: xcode12
script:
  - xcodebuild -quiet build test -project Moviesearch.xcodeproj -scheme Moviesearch -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.3' CODE_SIGNING_REQUIRED=NO
after_success:
  - bash <(curl -s https://codecov.io/bash)